# this is a dynamic storage provisioning
# reclaim policy --> retian(Keeps all the  data), delete(delete the data and  doisks as well) and recycle(delete all the data in the underlying storage).
# some storage  will  allow storage expansion and  some will not.

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-gold
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gold-storage