# this is a dynamic storage provisioning
# reclaim policy --> retian(Keeps all the  data), delete(delete the data and  doisks as well) and recycle(delete all the data in the underlying storage).
# some storage  will  allow storage expansion and  some will not.

---
# creating the  storage class as per the  admin requirements
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---
# creating the PVC using  storage class defined by the  admin
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-gold
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
storageClassName: gold-storage

---
#  creating the PVC using  storage class defined by the default class
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# Creating the pod using the default storage  and that  will create the pv and  disks as well.
apiVersion: v1
kind: Pod
metadata: 
  name: default-pvc-pod
spec:
  containers:
    - image: nginx
      name: default-pvc-cont
      volumeMounts:
        - mountPath: "/logs"
          name: my-pvc
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName:  pvc-default