#--------NODE SELECTOR ----------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector
spec:
  replicas: 3
  selector:
    matchLabels:  
      env: test
  template:
    metadata:
      name: node-selector
      labels:
        env: test
    spec:
      containers:
        - image: nginx
          name: nginx-cont
      nodeSelector:
        disktype: ssd


# --------------Nodename------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-name
spec:
  replicas: 2
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
        - image: nginx
          name: nodename-cont
      nodeName: <NODE NAME>

# ---------------NODE AFFINITY-Required-----------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      name: pod-affinity
      labels:
        env: test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoreDuringExecution:
            nodeSelectorTerms:
            - MatchExpressions:
                - key: disktype
                  operator: In
                  values:
                    - ssd
                    - thin
      containers:
        - image: nginx
          name: affinity-cont

# ----------------PREFERRED AFFINITY--------------------
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: node-affinity
  spec:
    replicas: 2
    selector:
      matchLabels:
        env: test
    template:
      metadata:
        name: pod-affinity
        labels:
          env: test
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoreDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: disktype
                  operator: In
                  values:
                    - ssd
                    - thin
        containers:
          - image: nginx
            name: nginx

# ---------------TAINT & TOLERANTS----------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-taint
spec:
  replicas: 2
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      name: pod-taints
      labels:
        env: test
    spec:
      containers:
        - name: nginx
          image: nginx
      tolerations:
        - key: "color"
          operator: "Equal"
          value: "green"
          effect: "NoSchedule"